library(readxl)
library(lubridate)
library(anytime)
library(janitor)
example1 = as.data.frame(read_excel('example1_adj.xlsx'), colClasses='string')
print(example1)
print(anydate(as.vector(unlist(example1['date1'], use.names = FALSE))))
print(convert_to_date(as.vector(unlist(example1['date1'], use.names = FALSE))))
print(parse_date_time(as.vector(unlist(example1['date1'], use.names = FALSE)),orders=c('ymd', 'dmy', 'mdy')))